# Generated by Django 5.1.3 on 2024-12-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sericultureapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
