# Generated by Django 5.1.3 on 2024-12-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sericultureapp', '0003_feedback_name_alter_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
