# Generated by Django 5.1.3 on 2024-12-13 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sericultureapp', '0005_remove_feedback_user_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidity', models.FloatField(help_text='Humidity in %')),
                ('feed_quantity', models.FloatField(help_text='Feed quantity in grams')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('silkworm_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_conditions', to='sericultureapp.silkwormbatch')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Egg', 'Egg'), ('Larva', 'Larva'), ('Pupa', 'Pupa'), ('Adult', 'Adult')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('silkworm_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='sericultureapp.silkwormbatch')),
            ],
        ),
    ]
