# Generated by Django 5.1.3 on 2024-12-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sericultureapp', '0006_environmentalcondition_growthstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_date', models.DateField(help_text='Date of feeding')),
                ('feed_time', models.TimeField(help_text='Time of feeding')),
                ('feed_quantity', models.FloatField(help_text='Quantity of feed in grams')),
                ('feed_type', models.CharField(help_text='Type of feed given', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Any observations or notes about the feeding', null=True)),
                ('silkworm_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_schedules', to='sericultureapp.silkwormbatch')),
            ],
        ),
    ]
