# Generated by Django 5.1.3 on 2024-12-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sericultureapp', '0008_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestordisease',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pestordisease',
            name='issue_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pestordisease',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
