# Generated by Django 5.1.3 on 2024-12-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sericultureapp', '0009_alter_pestordisease_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentalCondition',
        ),
    ]
